# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: DWB Enterprises
email: david@dwbenterprises.net
phone: 607-481-0888
phone-display: (607) 481-0888
description: "Manufacturer's Representative"
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site


# Build settings
markdown: kramdown

host: 0.0.0.0

# permalink: /project/:title
permalink: :title
